# Generated by Django 4.2.5 on 2024-05-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("BookName", models.CharField(max_length=100)),
                ("AuthorName", models.CharField(max_length=100)),
                ("Price", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
